### ISSUE TITLE
V5 roadmap

### ISSUE THREAD

**Issue by xingrz** [xingrz/rdt-editor#9]
Yet another maintenance window comes!

## Minor changes that already rolled out

- [x] GHA-based deploy
- [x] Tooling update
- [x] Lodash -> Radash
- [x] Vue props based CSS style -> CSS variables
- [x] Bugfix: Alignment of icons/texts in smaller preview panel
- [x] Clean up of states tracking of editor

## TODOs

- [x] [NaiveUI](https://www.naiveui.com/)
- [ ] Brace -> [Codemirror](https://codemirror.net/)
- [ ] Better icon finder
- [ ] Shift-click to open icon on Wikimedia Commons
- [ ] More shortcuts for manipulating icon overlays
